apiVersion: v1
kind: Service
metadata:
  name: octo-man-api
  labels:
    app.kubernetes.io/name: octo-man
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: octo-man
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
