apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-scan

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: shapoclyack
    includeSelectors: false

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  # NATS JetStream (message broker)
  -