apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner
  labels:
    app.kubernetes.io/name: shapoclyack
    app.kubernetes.io/component: scanner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  labels:
    app.kubernetes.io/name: shapoclyack
    app.kubernetes.io/component: api
