"use client";

import { useState } from "react";
import { Download, Eye, FileText } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { downloadArtifact, fetchArtifactText } from "@/lib/api";

const TEXT_EXTS = [".json", ".txt", ".md", ".csv", ".xml", ".log", ".yaml", ".yml"];

function isTextArtifact(path: string): boolean {
  const lower = path.toLowerCase();
  return TEXT_EXTS.some((ext) => lower.endsWith(ext));
}

function prettifyIfJson(path: string, text: string): string {
  if (!path.toLowerCase().endsWith(".json")) return text;
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

export function ArtifactsPanel({ runId, artifacts }: { runId: string; artifacts: string[] }) {
  const [previewPath, setPreviewPath] = useState<string | null>(null);
  const [previewText, setPreviewText] = useState("");
  const [previewLoading, setPreviewLoading] = useState(false);
  const [busyPath, setBusyPath] = useState<string | null>(null);

  const pdfReport = artifacts.find((path) => path === "summary.pdf");
  const rest = artifacts.filter((path) => path !== "summary.pdf");

  async function handleDownload(path: string) {
    setBusyPath(path);
    try {
      await downloadArtifact(runId, path);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Download failed");
    } finally {
      setBusyPath(null);
    }
  }

  async function handlePreview(path: string) {
    setPreviewPath(path);
    setPreviewLoading(true);
    setPreviewText("");
    try {
      const text = await fetchArtifactText(runId, path);
      setPreviewText(prettifyIfJson(path, text));
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Preview failed");
      setPreviewPath(null);
    } finally {
      setPreviewLoading(false);
    }
  }

  if (artifacts.length === 0) {
    return (
      <p className="rounded-xl border border-slate-800 bg-slate-900/60 px-4 py-8 text-center text-xs text-slate-400 backdrop-blur">
        No telemetry artifacts produced for this run.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      {pdfReport ? (
        <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-slate-800/80 bg-slate-900/80 p-4 shadow-lg backdrop-blur">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-rose-500/10 text-rose-400 border border-rose-500/20 shadow-md">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold text-slate-100">Executive Security PDF Report</p>
              <p className="text-xs text-slate-400">
                Leadership and executive summary generated by the scan engine.
              </p>
            </div>
          </div>
          <Button onClick={() => handleDownload(pdfReport)} disabled={busyPath === pdfReport} className="bg-rose-600 hover:bg-rose-500 text-white font-semibold text-xs gap-2">
            <Download className="h-4 w-4" />
            {busyPath === pdfReport ? "Downloading…" : "Download PDF"}
          </Button>
        </div>
      ) : null}

      <div className="overflow-hidden rounded-xl border border-slate-800/80 bg-slate-900/80 shadow-lg backdrop-blur">
        <table className="w-full text-left text-xs">
          <tbody className="divide-y divide-slate-800/60">
            {rest.map((path) => (
              <tr key={path} className="hover:bg-slate-800/40 transition-colors">
                <td className="px-4 py-3 font-mono font-bold text-slate-200">{path}</td>
                <td className="px-4 py-3 text-right">
                  <div className="flex justify-end gap-2">
                    {isTextArtifact(path) ? (
                      <Button variant="outline" size="sm" onClick={() => handlePreview(path)} className="border-slate-800 bg-slate-950 text-slate-300 hover:bg-slate-800 text-xs gap-1.5">
                        <Eye className="h-3.5 w-3.5" />
                        Preview
                      </Button>
                    ) : null}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(path)}
                      disabled={busyPath === path}
                      className="border-slate-800 bg-slate-950 text-slate-300 hover:bg-slate-800 text-xs gap-1.5"
                    >
                      <Download className="h-3.5 w-3.5" />
                      {busyPath === path ? "Downloading…" : "Download"}
                    </Button>
                  </div>
                </td>
              </tr>
            ))}
            {rest.length === 0 ? (
              <tr>
                <td className="px-4 py-6 text-center text-slate-400 text-xs" colSpan={2}>
                  Only the PDF report is available for this run.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      <Dialog open={Boolean(previewPath)} onOpenChange={(open) => !open && setPreviewPath(null)}>
        <DialogContent className="max-w-3xl bg-slate-900 border-slate-800 text-slate-100">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-slate-100">
              <span className="font-mono text-sm">{previewPath}</span>
              {previewPath ? <Badge variant="secondary" className="bg-sky-500/20 text-sky-300 border-sky-500/30 text-[10px]">PREVIEW</Badge> : null}
            </DialogTitle>
          </DialogHeader>
          {previewLoading ? (
            <div className="flex items-center justify-center py-8 text-slate-400 gap-2">
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-sky-400 border-t-transparent" />
              <span className="text-xs">Loading artifact text…</span>
            </div>
          ) : (
            <pre className="max-h-[60vh] overflow-auto rounded-lg border border-slate-800 bg-slate-950 p-4 font-mono text-xs leading-relaxed text-slate-200">
              {previewText}
            </pre>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
