"use client";

import { useState } from "react";
import { Download, Eye, FileText } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { downloadArtifact, fetchArtifactText } from "@/lib/api";

const TEXT_EXTS = [".json", ".txt", ".md", ".csv", ".xml", ".log", ".yaml", ".yml"];

function isTextArtifact(path: string): boolean {
  const lower = path.toLowerCase();
  return TEXT_EXTS.some((ext) => lower.endsWith(ext));
}

function prettifyIfJson(path: string, text: string): string {
  if (!path.toLowerCase().endsWith(".json")) return text;
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

export function ArtifactsPanel({ runId, artifacts }: { runId: string; artifacts: string[] }) {
  const [previewPath, setPreviewPath] = useState<string | null>(null);
  const [previewText, setPreviewText] = useState("");
  const [previewLoading, setPreviewLoading] = useState(false);
  const [busyPath, setBusyPath] = useState<string | null>(null);

  const pdfReport = artifacts.find((path) => path === "summary.pdf");
  const rest = artifacts.filter((path) => path !== "summary.pdf");

  async function handleDownload(path: string) {
    setBusyPath(path);
    try {
      await downloadArtifact(runId, path);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Download failed");
    } finally {
      setBusyPath(null);
    }
  }

  async function handlePreview(path: string) {
    setPreviewPath(path);
    setPreviewLoading(true);
    setPreviewText("");
    try {
      const text = await fetchArtifactText(runId, path);
      setPreviewText(prettifyIfJson(path, text));
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Preview failed");
      setPreviewPath(null);
    } finally {
      setPreviewLoading(false);
    }
  }

  if (artifacts.length === 0) {
    return (
      <p className="rounded-md border bg-white px-3 py-6 text-center text-sm text-muted-foreground">
        No artifacts produced for this run.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      {pdfReport ? (
        <div className="flex items-center justify-between rounded-lg border bg-white p-4">
          <div className="flex items-center gap-3">
            <FileText className="h-8 w-8 text-rose-600" />
            <div>
              <p className="font-medium text-slate-900">Business PDF report</p>
              <p className="text-xs text-muted-foreground">
                Leadership / ticket-ready summary generated by the scanner.
              </p>
            </div>
          </div>
          <Button onClick={() => handleDownload(pdfReport)} disabled={busyPath === pdfReport}>
            <Download className="mr-2 h-4 w-4" />
            {busyPath === pdfReport ? "Downloading…" : "Download PDF"}
          </Button>
        </div>
      ) : null}

      <div className="overflow-hidden rounded-lg border bg-white">
        <table className="w-full text-sm">
          <tbody>
            {rest.map((path) => (
              <tr key={path} className="border-b border-slate-100 last:border-0">
                <td className="px-4 py-2 font-mono text-xs text-slate-700">{path}</td>
                <td className="px-4 py-2 text-right">
                  <div className="flex justify-end gap-2">
                    {isTextArtifact(path) ? (
                      <Button variant="outline" size="sm" onClick={() => handlePreview(path)}>
                        <Eye className="mr-1 h-3.5 w-3.5" />
                        View
                      </Button>
                    ) : null}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(path)}
                      disabled={busyPath === path}
                    >
                      <Download className="mr-1 h-3.5 w-3.5" />
                      {busyPath === path ? "…" : "Download"}
                    </Button>
                  </div>
                </td>
              </tr>
            ))}
            {rest.length === 0 ? (
              <tr>
                <td className="px-4 py-6 text-center text-muted-foreground" colSpan={2}>
                  Only the PDF report is available for this run.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      <Dialog open={Boolean(previewPath)} onOpenChange={(open) => !open && setPreviewPath(null)}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <span className="font-mono text-sm">{previewPath}</span>
              {previewPath ? <Badge variant="secondary">preview</Badge> : null}
            </DialogTitle>
          </DialogHeader>
          {previewLoading ? (
            <p className="text-sm text-muted-foreground">Loading…</p>
          ) : (
            <pre className="max-h-[60vh] overflow-auto rounded-md bg-slate-950 p-4 text-xs leading-relaxed text-slate-100">
              {previewText}
            </pre>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
