from __future__ import annotations

from pathlib import Path

import pytest
from pydantic import ValidationError

from scanner.pipeline import dns_resolvers
from scanner.pipeline.config_schema import DnsConfig
from scanner.pipeline.dns_resolvers import (
    host_port,
    parse_resolver,
    scan_resolvers,
    system_resolvers,
)


def _resolv_conf(tmp_path: Path, text: str) -> Path:
    path = tmp_path / "resolv.conf"
    path.write_text(text, encoding="utf-8")
    return path


def test_system_resolvers_are_the_nameserver_lines_in_file_order(tmp_path: Path):
    path = _resolv_conf(
        tmp_path,
        "# generated by NetworkManager\n"
        "search corp.example\n"
        "nameserver 10.1.0.53\n"
        "; nameserver 9.9.9.9\n"
        "nameserver 2001:db8::53\n"
        "nameserver fe80::1%eth0\n"
        "nameserver 10.1.0.53\n"
        "nameserver resolver.corp.example\n"
        "nameserver\n"
        "options ndots:2 rotate\n",
    )
    assert system_resolvers(path) == ["10.1.0.53", "2001:db8::53", "fe80::1%eth0"]


def test_no_nameserver_means_the_loopback_resolver_not_an_empty_list(tmp_path: Path):
    # An empty list would let nuclei fall back to its public resolvers.
    assert system_resolvers(_resolv_conf(tmp_path, "search corp.example\n")) == ["127.0.0.1"]
    assert system_resolvers(tmp_path / "missing") == ["127.0.0.1"]


def test_scan_resolvers_prefers_the_config_and_reads_resolv_conf_at_call_time(
    tmp_path: Path, monkeypatch
):
    monkeypatch.setattr(dns_resolvers, "RESOLV_CONF", _resolv_conf(tmp_path, "nameserver 10.9.9.9\n"))
    assert scan_resolvers([]) == ["10.9.9.9"]
    assert scan_resolvers(["10.0.0.53"]) == ["10.0.0.53"]


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("10.0.0.53", ("10.0.0.53", 53)),
        ("10.0.0.53:5353", ("10.0.0.53", 5353)),
        ("2001:db8::53", ("2001:db8::53", 53)),
        ("[2001:db8::53]", ("2001:db8::53", 53)),
        ("[2001:db8::53]:5353", ("2001:db8::53", 5353)),
        (" 10.0.0.53 ", ("10.0.0.53", 53)),
    ],
)
def test_parse_resolver_accepts_address_literals(value: str, expected: tuple[str, int]):
    assert parse_resolver(value) == expected


@pytest.mark.parametrize(
    "value",
    [
        "dns.corp.example",
        "dns.corp.example:53",
        "10.0.0.53:0",
        "10.0.0.53:65536",
        "10.0.0.53:",
        "10.0.0.53:x",
        "[2001:db8::53]x",
        "[2001:db8::53",
        "udp:10.0.0.53",
        "",
    ],
)
def test_parse_resolver_rejects_anything_else(value: str):
    with pytest.raises(ValueError):
        parse_resolver(value)


def test_host_port_brackets_ipv6_and_always_names_the_port():
    assert host_port("10.0.0.53") == "10.0.0.53:53"
    assert host_port("2001:db8::53") == "[2001:db8::53]:53"
    assert host_port("[2001:db8::53]:5353") == "[2001:db8::53]:5353"


def test_dns_config_defaults_to_the_system_resolvers():
    assert DnsConfig().resolvers == []


def test_dns_config_refuses_a_resolver_given_by_name():
    with pytest.raises(ValidationError, match="not an IP address"):
        DnsConfig(resolvers=["10.0.0.53", "dns.corp.example"])
