"""SLO Prometheus rules stay aligned with exported series (#186, #334)."""

from __future__ import annotations

from pathlib import Path

import yaml

from tests import metric_catalogue

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "k8s/shapoclyack/examples/prometheus-slo.rules.yaml"
CRD = ROOT / "k8s/shapoclyack/examples/prometheusrule-slo.example.yaml"
# The same rules as part of the opt-in base/monitoring component (#334).
COMPONENT_CRD = ROOT / "k8s/shapoclyack/base/monitoring/prometheusrule-slo.yaml"


def _load_rules() -> dict:
    return yaml.safe_load(RULES.read_text(encoding="utf-8"))


def test_rules_file_has_every_slo_and_both_scheduler_invariants():
    data = _load_rules()
    alerts = [rule["alert"] for group in data["groups"] for rule in group["rules"]]
    for name in (
        "ShapoclyackApiAvailabilityFastBurn",
        "ShapoclyackApiAvailabilitySlowBurn",
        "ShapoclyackApiReadLatencyP95",
        "ShapoclyackJobCompletionBudget",
        "ShapoclyackJobDurationExceedsHistogram",
        "ShapoclyackClickHouseIngestLag",
        "ShapoclyackClickHouseIngestStale",
        "ShapoclyackClickHouseIngestErrors",
        "ShapoclyackEndpointInventoryAcceptance",
        "ShapoclyackLoginLimiterTripped",
        "ShapoclyackLoginFailuresElevated",
        "ShapoclyackSchedulerSplitBrain",
        "ShapoclyackSchedulerNoLeader",
        "ShapoclyackNatsOutboxBacklog",
        "ShapoclyackNatsOutboxAssetEventsBacklog",
        "ShapoclyackNatsOutboxDead",
        "ShapoclyackNatsOutboxDropping",
        "ShapoclyackAssetEventsSkipped",
        "ShapoclyackDbPoolSaturated",
        "ShapoclyackDbPoolCheckoutTimeouts",
        "ShapoclyackSensorsStale",
        "ShapoclyackNoSensorOnline",
    ):
        assert name in alerts, name


def test_every_octo_series_in_the_rules_is_exported():
    # From the registry, not from a list kept beside it: a series renamed in
    # api/services/metrics.py fails here instead of silencing an alert (#334).
    unknown = metric_catalogue.unknown_series(RULES.read_text(encoding="utf-8"))
    assert not unknown, f"rules mention series the API does not export: {sorted(unknown)}"


def test_prometheusrule_wrapper_matches_the_rules_file():
    rules = _load_rules()
    crd = yaml.safe_load(CRD.read_text(encoding="utf-8"))
    assert crd["kind"] == "PrometheusRule"
    assert crd["metadata"]["namespace"] == "network-scan"
    assert crd["spec"]["groups"] == rules["groups"]


def test_the_monitoring_component_carries_the_same_rules():
    """Generated by the same script as the example; namespace-less, because the
    component's own transformer sets it."""
    rules = _load_rules()
    crd = yaml.safe_load(COMPONENT_CRD.read_text(encoding="utf-8"))
    assert crd["kind"] == "PrometheusRule"
    assert "namespace" not in crd["metadata"]
    assert crd["spec"]["groups"] == rules["groups"]


def test_scheduler_alerts_require_the_series_to_exist():
    """Absent scrape must not look like 'no leader'."""
    text = RULES.read_text(encoding="utf-8")
    assert "count(octo_scheduler_is_leader) > 0" in text
    assert "for: 5m" in text
    assert "for: 10m" in text


def test_nats_outbox_alerts_are_split_by_kind():
    text = RULES.read_text(encoding="utf-8")
    assert 'octo_nats_outbox_backlog{kind="ingest",status="stale"}' in text
    assert 'octo_nats_outbox_backlog{kind="asset_event",status="stale"}' in text
    assert "max by (kind) (octo_nats_outbox_backlog{status=\"dead\"})" in text
