"""The hash-pinned Python locks and the installs that depend on them (#313).

``requirements*.txt`` are what people edit; the ``*.lock`` files compiled from
them by ``scripts/lock-python-deps.sh`` are what the images and pipelines
install, with ``pip install --require-hashes``. That only protects anything
while three things stay true, and each is cheap to break without noticing:

* the lock still says what its input says — a bump in ``requirements.txt``
  without a regenerated lock builds the old version, and a dependency added
  to the input but not to the lock fails the image build at the worst time;
* every install goes through a lock — one ``pip install -r requirements.txt``
  left in a Dockerfile or pipeline and the hashes protect nothing there;
* the header is the command Renovate can replay: its pip-compile manager
  re-runs the header verbatim when it bumps a dependency and gives up on an
  option it does not know, which would leave that lock to rot silently.

All of it is checked offline, from the files alone: re-resolving would need
PyPI, and the resolution is not what drifts — the files are.
"""

from __future__ import annotations

import os
import re
import shlex
import subprocess
from collections import defaultdict
from pathlib import Path

import pytest
import yaml
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCK_SCRIPT = REPO_ROOT / "scripts" / "lock-python-deps.sh"

_HEADER = re.compile(
    r"\A# This file was autogenerated by uv via the following command:\n"
    r"#    (?P<command>uv pip compile [^\n]+)\n"
)
_ENTRY = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?:\[(?P<extras>[^\]]*)\])?==(?P<version>[^\s;\\]+)"
)
_HASH = re.compile(r"^\s+--hash=sha256:[0-9a-f]{64}\s*\\?$")


def _lock_table() -> dict[str, str]:
    """lock -> input, as scripts/lock-python-deps.sh declares them."""
    body = LOCK_SCRIPT.read_text(encoding="utf-8")
    block = re.search(r"^LOCKS=\((?P<items>.*?)^\)", body, re.MULTILINE | re.DOTALL)
    assert block, "LOCKS=( … ) moved in lock-python-deps.sh; update this test"
    pairs = re.findall(r'"([^":]+):([^"]+)"', block.group("items"))
    assert pairs
    return dict(pairs)


LOCKS = _lock_table()


def _lock_entries(lock: str) -> dict[str, dict]:
    """Package entries of a lock: version, marker, hashes and `via` sources."""
    entries: dict[str, dict] = {}
    current: dict | None = None
    in_via = False
    for raw in (REPO_ROOT / lock).read_text(encoding="utf-8").splitlines():
        match = _ENTRY.match(raw)
        if match:
            name = canonicalize_name(match.group("name"))
            marker = raw.split(";", 1)[1].rstrip(" \\") if ";" in raw else None
            current = entries.setdefault(
                name,
                {"versions": set(), "hashes": 0, "via": set(), "markers": set(), "extras": set()},
            )
            current["versions"].add(match.group("version"))
            extras = match.group("extras") or ""
            current["extras"] |= {canonicalize_name(e) for e in extras.split(",") if e.strip()}
            current["markers"].add(marker)
            in_via = False
            continue
        if current is None:
            continue
        stripped = raw.strip()
        if _HASH.match(raw):
            current["hashes"] += 1
        elif stripped.startswith("# via"):
            rest = stripped.removeprefix("# via").strip()
            in_via = not rest
            if rest:
                current["via"].add(rest)
        elif in_via and stripped.startswith("#   "):
            current["via"].add(stripped.removeprefix("#").strip())
        elif stripped and not stripped.startswith("#"):
            raise AssertionError(f"{lock}: unexpected line {raw!r}")
    return entries


def _input_requirements(path: Path, seen: set[Path] | None = None) -> dict[Path, list[Requirement]]:
    """Requirements per input file, following `-r` includes."""
    seen = set() if seen is None else seen
    if path in seen:
        return {}
    seen.add(path)
    found: dict[Path, list[Requirement]] = {path: []}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = re.sub(r"(^|\s)#.*$", "", raw).strip()
        if not line:
            continue
        if line.startswith(("-r ", "--requirement ")):
            found.update(_input_requirements(path.parent / line.split(None, 1)[1], seen))
            continue
        assert not line.startswith("-"), f"{path.name}: option {line!r} is not handled here"
        found[path].append(Requirement(line))
    return found


# --- the table, the files and the headers agree ------------------------------


def test_every_requirements_file_is_compiled_into_a_lock():
    """A new requirements-*.txt nobody locks is installed unhashed or not at all."""
    reachable = set()
    for lock_input in LOCKS.values():
        reachable |= set(_input_requirements(REPO_ROOT / lock_input))
    inputs = set(REPO_ROOT.glob("requirements*.txt"))
    assert inputs - reachable == set(), "add them to LOCKS in scripts/lock-python-deps.sh"


def test_every_lock_on_disk_is_one_the_script_regenerates():
    assert {p.name for p in REPO_ROOT.glob("*.lock")} == set(LOCKS)


@pytest.mark.parametrize("lock", sorted(LOCKS))
def test_lock_header_is_the_command_renovate_replays(lock: str):
    text = (REPO_ROOT / lock).read_text(encoding="utf-8")
    header = _HEADER.match(text)
    assert header, f"{lock} has no uv header; regenerate it with scripts/lock-python-deps.sh"
    # Exactly this, in this order: --universal and the --python-version floor
    # are what make one lock valid on amd64 and arm64 and on 3.11 and 3.12;
    # --no-strip-extras keeps `psycopg[binary]` visible, so the extras test
    # below can see an input's extras drift; --generate-hashes is the point;
    # and Renovate only accepts options it knows, spelled --opt=value.
    assert shlex.split(header.group("command")) == [
        "uv",
        "pip",
        "compile",
        "--universal",
        "--no-strip-extras",
        "--generate-hashes",
        "--python-version=3.11",
        f"--output-file={lock}",
        LOCKS[lock],
    ]


# --- what is in a lock -------------------------------------------------------


@pytest.mark.parametrize("lock", sorted(LOCKS))
def test_every_locked_package_is_pinned_and_hashed(lock: str):
    entries = _lock_entries(lock)
    assert entries, f"{lock} lists no packages"
    unhashed = sorted(name for name, entry in entries.items() if entry["hashes"] == 0)
    assert not unhashed, f"{lock}: no --hash for {unhashed}"


@pytest.mark.parametrize("lock", sorted(LOCKS))
def test_lock_satisfies_every_direct_requirement(lock: str):
    """The drift that matters: an input bumped, added or removed without
    regenerating the lock. The image would build the old set, and a pin
    reviewed in requirements.txt would not be the one that ships."""
    entries = _lock_entries(lock)
    for source, requirements in _input_requirements(REPO_ROOT / LOCKS[lock]).items():
        for requirement in requirements:
            name = canonicalize_name(requirement.name)
            assert name in entries, f"{source.name}: {requirement} is missing from {lock}"
            for version in entries[name]["versions"]:
                assert requirement.specifier.contains(version, prereleases=True), (
                    f"{source.name} asks for {requirement}, {lock} has {name}=={version}:"
                    " run scripts/lock-python-deps.sh"
                )


@pytest.mark.parametrize("lock", sorted(LOCKS))
def test_lock_keeps_every_extra_its_inputs_ask_for(lock: str):
    """`psycopg[binary]` -> `psycopg[binary,pool]` without relocking passes the
    version check and ships an image without psycopg-pool. The lock keeps the
    extras (--no-strip-extras), so the drift is visible here."""
    entries = _lock_entries(lock)
    for source, requirements in _input_requirements(REPO_ROOT / LOCKS[lock]).items():
        for requirement in requirements:
            wanted = {canonicalize_name(e) for e in requirement.extras}
            locked = entries[canonicalize_name(requirement.name)]["extras"]
            assert wanted <= locked, (
                f"{source.name} asks for {requirement}, {lock} locks extras {sorted(locked)}:"
                " run scripts/lock-python-deps.sh"
            )


@pytest.mark.parametrize("lock", sorted(LOCKS))
def test_lock_has_nothing_its_inputs_no_longer_ask_for(lock: str):
    """uv annotates each direct dependency with `via -r <file>`; one whose
    input line is gone is a stale lock carrying a package nobody reviewed."""
    wanted = {
        source.name: {canonicalize_name(r.name) for r in requirements}
        for source, requirements in _input_requirements(REPO_ROOT / LOCKS[lock]).items()
    }
    for name, entry in _lock_entries(lock).items():
        for via in entry["via"]:
            if via.startswith("-r "):
                source = via.removeprefix("-r ").strip()
                assert name in wanted.get(source, set()), (
                    f"{lock}: {name} is locked as a direct dependency of {source},"
                    " which no longer lists it"
                )


def test_a_package_has_one_version_in_every_lock():
    """CI installs requirements-dev.lock and the images the others; a shared
    package at two versions would mean the tests ran against a set that does
    not ship."""
    versions: dict[str, dict[str, set[str]]] = defaultdict(dict)
    for lock in LOCKS:
        for name, entry in _lock_entries(lock).items():
            versions[name][lock] = entry["versions"]
    split = {
        name: {lock: sorted(v) for lock, v in per_lock.items()}
        for name, per_lock in versions.items()
        if len({frozenset(v) for v in per_lock.values()}) > 1
    }
    assert not split, f"regenerate the locks together: {split}"


# --- every install goes through a lock ---------------------------------------

# Files that run `pip install`. Scanned whole, so a new install line anywhere in
# them is held to the rule without anyone remembering to add it here.
_INSTALLERS = [
    "Dockerfile",
    "Dockerfile.api",
    "Dockerfile.allinone",
    "Jenkinsfile",
    "Jenkinsfile.publish",
    ".github/workflows/ci.yml",
    ".github/workflows/pr-gate.yml",
    ".github/workflows/docker-publish.yml",
    ".github/workflows/load-test.yml",
    ".github/actions/synthetic-load-test/action.yml",
    "scripts/ci-lint.sh",
]

# Installs that deliberately do not go through a lock, and why. Matched as a
# substring of the install command, so rewording one is a decision made here.
_UNLOCKED = {
    # The Smoke stage adds pytest to the throwaway container it tests the
    # just-built image in; nothing it installs ships, and the image's own
    # dependencies were installed from the lock by the Dockerfile.
    "pip install --quiet --no-cache-dir --user pytest": "Jenkinsfile",
}

def _pip_installs(text: str) -> list[str]:
    """Every `pip install` command in a file, continuation lines joined."""
    commands = []
    for match in re.finditer(r"\bpip3? install\b", text):
        line_start = text.rfind("\n", 0, match.start()) + 1
        prefix = text[line_start : match.start()]
        # Prose, not a command: a comment, or a message telling someone what
        # to run ("[lint]   python -m pip install ruff==…").
        if "#" in prefix or "//" in prefix or "echo" in prefix:
            continue
        end = match.end()
        while end < len(text):
            if text[end] == ";" or text.startswith(("&&", "||"), end):
                break
            if text[end] == "\n" and text[end - 1] != "\\":
                break
            end += 1
        commands.append(re.sub(r"\\\n\s*", " ", text[match.start() : end]).strip())
    return commands


@pytest.mark.parametrize("path", _INSTALLERS)
def test_every_install_is_hash_checked_from_a_lock(path: str):
    text = (REPO_ROOT / path).read_text(encoding="utf-8")
    for command in _pip_installs(text):
        if any(allowed in command for allowed, where in _UNLOCKED.items() if where == path):
            continue
        assert "--require-hashes" in command, f"{path}: {command!r} is not hash-checked"
        # Hashes do not reach the build dependencies of an sdist: pip installs
        # those into its isolated build environment unchecked. Every locked
        # package ships a wheel for the image and CI platforms, so refusing
        # sdists outright costs nothing and closes that gap.
        assert "--only-binary=:all:" in command, f"{path}: {command!r} may build an sdist"
        targets = re.findall(r"-r\s+(\S+)", command)
        assert targets, f"{path}: {command!r} installs no requirements file"
        for target in targets:
            assert target.strip("\"'").endswith(".lock"), (
                f"{path}: {command!r} installs {target}, not a lock"
            )


def test_the_unlocked_installs_still_exist():
    """An exception whose line is gone would silently cover the next one."""
    for allowed, path in _UNLOCKED.items():
        assert allowed in (REPO_ROOT / path).read_text(encoding="utf-8"), (allowed, path)


def test_the_lint_installs_ruff_from_the_lock_with_its_hashes(tmp_path: Path):
    """scripts/ci-lint.sh --install cuts the ruff entry out of the dev lock.

    A stub `pip` records what it was handed; the requirement file has to be
    the pin and its hashes and nothing else, so the hash check covers exactly
    the Ruff the lint then insists on.
    """
    pin = next(
        line.strip()
        for line in (REPO_ROOT / "requirements-dev.txt").read_text(encoding="utf-8").splitlines()
        if line.startswith("ruff==")
    )
    bindir = tmp_path / "bin"
    bindir.mkdir()
    argv_file = tmp_path / "pip-argv"
    req_copy = tmp_path / "pip-req"
    (bindir / "pip").write_text(
        "#!/usr/bin/env bash\n"
        f'printf "%s\\n" "$@" > "{argv_file}"\n'
        'while [[ $# -gt 0 ]]; do [[ "$1" == "-r" ]] && cp "$2" "' + str(req_copy) + '"; shift; done\n',
        encoding="utf-8",
    )
    (bindir / "ruff").write_text(
        "#!/usr/bin/env bash\n"
        f'if [[ "$1" == "--version" ]]; then echo "ruff {pin.removeprefix("ruff==")}"; fi\n',
        encoding="utf-8",
    )
    for stub in bindir.iterdir():
        stub.chmod(0o755)
    result = subprocess.run(
        [str(REPO_ROOT / "scripts" / "ci-lint.sh"), "--install"],
        cwd=REPO_ROOT,
        env=dict(os.environ, PATH=f"{bindir}:{os.environ['PATH']}"),
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    argv = argv_file.read_text(encoding="utf-8").split()
    assert argv[0] == "install"
    assert {"--require-hashes", "--only-binary=:all:", "--no-deps"} <= set(argv)
    lines = req_copy.read_text(encoding="utf-8").splitlines()
    assert lines[0] == f"{pin} \\"
    assert len(lines) > 1 and all(_HASH.match(line) for line in lines[1:]), lines


def test_installers_list_covers_every_file_that_runs_pip():
    candidates = [
        *REPO_ROOT.glob("Dockerfile*"),
        *REPO_ROOT.glob("Jenkinsfile*"),
        *(REPO_ROOT / ".github").rglob("*.yml"),
        *(REPO_ROOT / "scripts").glob("ci-*.sh"),
    ]
    running = {
        str(p.relative_to(REPO_ROOT))
        for p in candidates
        if _pip_installs(p.read_text(encoding="utf-8"))
    }
    assert running <= set(_INSTALLERS), running - set(_INSTALLERS)


def _setup_python_steps():
    for path in sorted((REPO_ROOT / ".github").rglob("*.yml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        stack = [doc]
        while stack:
            node = stack.pop()
            if isinstance(node, dict):
                if str(node.get("uses", "")).startswith("actions/setup-python@"):
                    yield path.relative_to(REPO_ROOT), node
                stack.extend(node.values())
            elif isinstance(node, list):
                stack.extend(node)


def test_the_pip_cache_is_keyed_on_the_lock_it_installs():
    """setup-python's `cache: pip` keys on requirements*.txt by default, which
    no longer change when a transitive pin does: a relock would reuse a stale
    cache key. The lock is what is installed, so it is the key."""
    steps = list(_setup_python_steps())
    assert steps, "no setup-python step found; the walk is broken"
    for path, step in steps:
        options = step.get("with") or {}
        if options.get("cache") != "pip":
            continue
        keyed = str(options.get("cache-dependency-path", ""))
        assert keyed.endswith(".lock") and (REPO_ROOT / keyed).exists(), (path, keyed)
