apiVersion: apps/v1
kind: Deployment
metadata:
  name: octo-man-api
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/onixus/shapoclyack-api:shapoclyack-0.33
          env:
            - name: OCTO_ALLOW_SCAN_START
              value: "false"
            - name: OCTO_JOB_EXECUTION_MODE
              value: local
          resources:
            requests:
              cpu: "100m"
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /app/scanner/output
              subPath: output
              readOnly: true
            - name: data
              mountPath: /app/scanner/state
              subPath: state
              readOnly: true
            - name: config
              mountPath: /app/scanner/config
              readOnly: true
