import {
  BookText,
  CalendarDays,
  Database,
  FileText,
  Globe2,
  Home,
  Laptop,
  Play,
  Radar,
  Server,
  Share2,
  ShieldAlert,
  Siren,
  SlidersHorizontal,
  SquareKanban,
  Timer,
  Users,
} from "lucide-react";

export const NAV = [
  { href: "/", labelKey: "nav.dashboard", icon: Home },
  { href: "/vulnerabilities", labelKey: "nav.vulnerabilities", icon: ShieldAlert },
  { href: "/remediation", labelKey: "nav.remediation", icon: SquareKanban },
  { href: "/assets", labelKey: "nav.assets", icon: Database },
  { href: "/exposure", labelKey: "nav.exposure", icon: Radar },
  { href: "/threats", labelKey: "nav.threats", icon: Siren },
  { href: "/tenants", labelKey: "nav.tenants", icon: Users },
  { href: "/agents", labelKey: "nav.agents", icon: Server },
  { href: "/jobs", labelKey: "nav.jobs", icon: CalendarDays },
  { href: "/schedules", labelKey: "nav.schedules", icon: Timer },
  { href: "/wordlists", labelKey: "nav.wordlists", icon: BookText },
  { href: "/runs", labelKey: "nav.runs", icon: Play },
  { href: "/endpoints", labelKey: "nav.endpoints", icon: Laptop },
  { href: "/attack-surface", labelKey: "nav.attackSurface", icon: Share2 },
  { href: "/geo", labelKey: "nav.geo", icon: Globe2 },
  { href: "/reports", labelKey: "nav.reports", icon: FileText },
  { href: "/system", labelKey: "nav.system", icon: SlidersHorizontal },
] as const;
