import {
  BookText,
  CalendarDays,
  Database,
  FileText,
  Globe2,
  Home,
  Laptop,
  Play,
  Radar,
  Server,
  Share2,
  ShieldAlert,
  Siren,
  SlidersHorizontal,
  SquareKanban,
  Timer,
  Users,
} from "lucide-react";

export const NAV = [
  { href: "/", label: "Dashboard", icon: Home },
  { href: "/vulnerabilities", label: "Vulnerabilities", icon: ShieldAlert },
  { href: "/remediation", label: "Remediation", icon: SquareKanban },
  { href: "/assets", label: "Assets", icon: Database },
  { href: "/exposure", label: "Exposure", icon: Radar },
  { href: "/threats", label: "Threat intel", icon: Siren },
  { href: "/tenants", label: "Tenants", icon: Users },
  { href: "/agents", label: "Agents", icon: Server },
  { href: "/jobs", label: "Jobs", icon: CalendarDays },
  { href: "/schedules", label: "Schedules", icon: Timer },
  { href: "/wordlists", label: "Wordlists", icon: BookText },
  { href: "/runs", label: "Runs", icon: Play },
  { href: "/endpoints", label: "Endpoints", icon: Laptop },
  { href: "/attack-surface", label: "Attack Surface", icon: Share2 },
  { href: "/geo", label: "Geo Map", icon: Globe2 },
  { href: "/reports", label: "Reports", icon: FileText },
  { href: "/system", label: "System", icon: SlidersHorizontal },
] as const;
