apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: job-hostnetwork-patch.yaml
  - path: cronjob-hostnetwork-patch.yaml
  - path: api-replicas-patch.yaml
