#!/usr/bin/env python3
"""Build scanner/pipeline/pulse_data/services.tsv from the IANA service-name registry.

Pulse takes a port-to-name table through ``--services-db``. Without one it
looks for the Nmap data files on the host, which are under the NPSL, so the
sensor always passes this file instead (docs/adr/0002-replacing-nmap-functions.md).

Source: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv
(IANA registry, public domain; see docs/third-party.md). The file is NOT derived
from nmap-services.

Usage: build-pulse-services.py service-names-port-numbers.csv > scanner/pipeline/pulse_data/services.tsv
"""

from __future__ import annotations

import csv
import re
import sys
from collections.abc import Iterable

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9._+-]*$")


def build(rows: Iterable[dict[str, str]]) -> list[tuple[int, str, str]]:
    """First registered name per (port, tcp|udp); skips ranges, aliases and blanks."""
    chosen: dict[tuple[int, str], str] = {}
    for row in rows:
        name = (row.get("Service Name") or "").strip()
        port = (row.get("Port Number") or "").strip()
        proto = (row.get("Transport Protocol") or "").strip().lower()
        note = (row.get("Assignment Notes") or "").lower()
        if proto not in ("tcp", "udp") or not port.isdigit() or not name:
            continue
        # IANA flags alias rows ("www" for "http") itself.
        if "duplicate" in note and "should not be used" in note:
            continue
        # Lower-case labels; "/" or spaces would not survive the
        # whitespace-separated table format.
        name = name.lower()
        if not NAME_RE.match(name) or not 0 < int(port) < 65536:
            continue
        chosen.setdefault((int(port), proto), name)
    return sorted((port, proto, name) for (port, proto), name in chosen.items())


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    with open(argv[1], newline="", encoding="utf-8") as fh:
        entries = build(csv.DictReader(fh))
    print("# IANA Service Name and Transport Protocol Port Number Registry (public domain).")
    print("# Generated by scripts/build-pulse-services.py; do not edit by hand.")
    print("# Format (the one Pulse --services-db reads): name<TAB>port/proto")
    for port, proto, name in entries:
        print(f"{name}\t{port}/{proto}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
