apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-scan

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: network-scan-cli
    includeSelectors: false

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - job.yaml
  - cronjob.yaml

configMapGenerator:
  - name: scanner-config
    files:
      - config/k8s.yaml

generatorOptions:
  disableNameSuffixHash: true
