apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanner-data
  labels:
    app.kubernetes.io/name: network-scan-cli
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: <your-class>  # раскомментировать при необходимости
