apiVersion: v1
kind: Service
metadata:
  name: octo-man-nats
  labels:
    app.kubernetes.io/name: octo-man
    app.kubernetes.io/component: nats
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: octo-man
    app.kubernetes.io/component: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: monitor
      port: 8222
      targetPort: monitor
