apiVersion: batch/v1
kind: Job
metadata:
  name: network-scan
spec:
  activeDeadlineSeconds: 3600
  template:
    spec:
      containers:
        - name: scanner
          args:
            - --config
            - /app/scanner/config/k8s.yaml
            - --mode
            - safe
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
