apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: job-resources-patch.yaml
  - path: cronjob-resources-patch.yaml
  - path: api-resources-patch.yaml
